# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
# - Multiple values [jdbc:oracle:thin:@localhost:1521:XE, jdbc:postgresql://localhost:5432/MyPostgreSQL, jdbc:mysql://localhost:3306/mySqlDB] assigned to 'spring.datasource.url'. Values are merged into a yaml sequence node.
# - Multiple values [OracleDB, postgres, root] assigned to 'spring.datasource.username'. Values are merged into a yaml sequence node.
spring:
  application:
    name: Profile_Resource
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: OracleDB
    password: Nur@1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
---


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mydatabase
      username: mongod
      password: Nur@1234
---
spring:
  application:
    name: Profile_Resource
  datasource:
    url: jdbc:postgresql://localhost:5432/MyPostgreSQL
    username: postgres
    password: Nur@1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://localhost:27017/mydatabase
      username: mongod
      password: Nur@1234
