spring.application.name=Starter-Proj01_Standalone_EmployeeDetailsFind

# ===============================
# = SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# = ORACLE DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=hknit11am
spring.datasource.password=hari
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
